### ISSUE TITLE
FileSystemException during upload file

### ISSUE THREAD

**Issue by vincent2yui** [Nexific/dart_ftpclient#6]
Hi,

I received an error when I tried to upload a file in my FTP server. Kindly see the details below:

Cannot open file, path = 'upload.txt' (OS Error: No such file or directory, errno = 2)

As i checked, the file was successfully uploaded in the FTP server, but this error is showing in the debug console.

Also my app has a read/write permission in the phone.

Thank you,
Vincent

**Comment by virtualmarc** [comment]
Are you sure it has been successfully uploaded or is the file on the FTP Server empty?

This looks like you want to upload a file that does not exist on the phone in the current path.
Since file creation and upload are separated on FTP, it might have created an empty file on the Server but was not able to upload your local file because it was not found.

**Comment by vincent2yui** [comment]
I copied the file in the phone and it is now working fine with the correct file path. 

Appreciate the quick reply!
